version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  mongodb:
    image: mongo
    container_name: mongo
    environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mini-app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres_db
      - spring.datasource.username=root
      - spring.datasource.password=root

      - spring.data.mongodb.uri=mongodb://admin:admin@mongodb:27017/mongo_db?authSource=admin
    depends_on:
      - postgres
      - mongodb

volumes:
  postgres_data:
  mongo_data: