name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Start PostgreSQL and MongoDB containers
        run: docker compose up -d postgres mongodb

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          until docker exec postgres pg_isready -U root -d postgres_db; do sleep 1; done
          echo "PostgreSQL is ready!"

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB..."
          until nc -z localhost 27017; do sleep 1; done
          echo "MongoDB is ready!"

      - name: Build and test
        run: mvn -B test

      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: Test Results
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit
