name: Java App CI with Docker Compose + Test Results

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 23 before Maven build
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'  # You can choose a different distribution if needed
          cache: maven  # Caches Maven dependencies to speed up future runs

      - name: Build JAR
        run: mvn -B package

      - name: Show Docker and Compose versions
        run: |
          docker --version
          docker compose version

      - name: Start containers and run tests
        run: docker compose up --build --abort-on-container-exit

      # Ensure reports are copied from the container
      - name: Copy test reports from container
        run: |
          docker cp $(docker compose ps -q app):/app/target/surefire-reports ./surefire-reports
        if: always()

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: surefire-reports/*.xml

      - name: Shutdown containers
        if: always()
        run: docker compose down
