# .github/workflows/report.yml

name: Publish Test Results

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

permissions:
  actions: read
  contents: read
  checks: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Test Results
        uses: dorny/test-reporter@v2
        with:
          artifact: test-results            # artifact name
          name: Test Results                  # Name of the check run which will be created
          path: '*.xml'                     # Path to test results (inside artifact .zip)
          reporter: java-junit              # Format of test results
