# .github/workflows/report.yml

name: Report Test Results

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

permissions:
  checks: write
  pull-requests: write

jobs:
  report:
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download test results artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Build and Test 
          name: test-results      
          path: test-results

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: test-results/*.xml
          reporter: java-junit
